Controllers/ProfileController.cs
using LeBarbier.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Web.Mvc;

namespace LeBarbier.Controllers
{
    public class ProfileController : Controller
    {
        private DBContext db = new DBContext();

        [HttpGet]
        public ActionResult Index()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Auth");
            }

            var userId = int.Parse(User.Identity.Name);
            var userProfile = db.Users.Include(u => u.Reservations).FirstOrDefault(u => u.IdUser == userId);

            if (userProfile == null)
            {
                return HttpNotFound();
            }

            return View(userProfile);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteReservation(int id)
        {
            var userId = int.Parse(User.Identity.Name);

            var reservation = db.Reservations
                                .Include(r => r.ReservationServices)
                                .FirstOrDefault(r => r.IdReservation == id && r.Id_User == userId);

            if (reservation == null)
            {
                return HttpNotFound();
            }

            db.ReservationServices.RemoveRange(reservation.ReservationServices);

            db.Reservations.Remove(reservation);

            try
            {
                db.SaveChanges();
            }
            catch (DbUpdateException ex)
            {
                throw ex;
            }

            return RedirectToAction("Index");
        }
    }
}

Controllers/ReservationsController.cs
using LeBarbier.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace LeBarbier.Controllers
{
    public class ReservationsController : Controller
    {
        private DBContext db = new DBContext();

        public ActionResult Index()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Auth");
            }

            var userId = int.Parse(User.Identity.Name);
            var reservations = db.Reservations.Where(r => r.Id_User == userId).ToList();
            var user = db.Users.Find(userId);
            ViewBag.Name = user.FirstName;
            return View(reservations);
        }

        [HttpGet]
        public ActionResult Create(DateTime selectedDate)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Auth");
            }

            DateTime currentDate = selectedDate;

            ViewBag.Services = db.OfferedServices.ToList();
            ViewBag.SelectedDate = currentDate.ToString("yyyy-MM-dd");

            var allTimes = new List<TimeSpan>
            {
                new TimeSpan(8, 0, 0),
                new TimeSpan(9, 0, 0),
                new TimeSpan(10, 0, 0),
                new TimeSpan(11, 0, 0),
                new TimeSpan(12, 0, 0),
                new TimeSpan(15, 0, 0),
                new TimeSpan(16, 0, 0),
                new TimeSpan(17, 0, 0),
                new TimeSpan(18, 0, 0)
            };

            var bookedTimes = db.Reservations
                                .Where(r => r.ReservationDate == currentDate)
                                .Select(r => r.ReservationTime)
                                .ToList();

            var availableTimes = allTimes.Except(bookedTimes).ToList();
            ViewBag.AvailableTimes = availableTimes;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int serviceId, DateTime reservationDate, string reservationTime)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Auth");
            }

            var userId = int.Parse(User.Identity.Name);
            var timeSpan = TimeSpan.Parse(reservationTime);

            var reservation = new Reservation
            {
                Id_User = userId,
                ReservationDate = reservationDate,
                ReservationTime = timeSpan
            };

            db.Reservations.Add(reservation);
            db.SaveChanges();

            var reservationService = new ReservationService
            {
                Id_Reservation = reservation.IdReservation,
                Id_OfferedServices = serviceId
            };

            db.ReservationServices.Add(reservationService);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Auth");
            }

            var reservation = db.Reservations.Find(id);
            if (reservation != null)
            {
                db.Reservations.Remove(reservation);
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        public ActionResult GetReservations()
        {

            var reservations = db.Reservations
                .Select(r => new
                {
                    IdService = db.ReservationServices
                                  .Where(rs => rs.Id_Reservation == r.IdReservation)
                                  .Select(rs => rs.Id_OfferedServices)
                                  .FirstOrDefault(),
                    r.ReservationDate,
                    r.ReservationTime
                })
                .ToList()
                .Select(r => new
                {
                    title = db.OfferedServices.FirstOrDefault(s => s.IdOfferedServices == r.IdService)?.ServiceName ?? "Unknown Service",
                    start = r.ReservationDate.Add(r.ReservationTime),
                }).ToList();

            return Json(reservations, JsonRequestBehavior.AllowGet);
        }


    }
}

Controllers/ServicesController.cs
using LeBarbier.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LeBarbier.Controllers
{
    public class ServicesController : Controller
    {
        private DBContext db = new DBContext();
        public ActionResult AllServices()
        {
            var allServices = db.OfferedServices.ToList();

            return View(allServices);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="/Content/imgs/logo.jpeg">
    <title>@ViewBag.Title - LeBarbier</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link href="https://cdn.jsdelivr.net/npm/fullcalendar@5.9.0/main.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@5.9.0/main.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@5.9.0/locales-all.min.js"></script>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400..700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Bodoni+Moda+SC:ital,opsz,wght@0,6..96,400..900;1,6..96,400..900&family=Cormorant+Garamond:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">

    <style>
        .title-brand {
            font-family: "Dancing Script", cursive;
            font-size: 50px;
        }
    </style>

</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm ">
        <div class="container-fluid">
            @if (User.Identity.IsAuthenticated)
            {
                if (User.IsInRole("Admin"))
                {
                    @Html.ActionLink("LeBarbier", "Index", "Admin", new { area = "" }, new { @class = "navbar-brand title-brand" })
                }
                else
                {
                    @Html.ActionLink("LeBarbier", "Index", "Reservations", new { area = "" }, new { @class = "navbar-brand title-brand" })
                }
            }
            else
            {
                @Html.ActionLink("LeBarbier", "WelcomePage", "Home", new { area = "" }, new { @class = "navbar-brand title-brand" })
            }
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Attiva/Disattiva spostamento" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Servizi", "AllServices", "Services", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Prenota", "Index", "Reservations", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Contatti", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Area Personale", "Index", "Profile", new { area = "" }, new { @class = "nav-link" })</li>
                        <li class="ml-auto">
                            @using (Html.BeginForm("Logout", "Auth"))
                            {
                                @Html.AntiForgeryToken()
                                <button type="submit" class="nav-link border-0 bg-transparent">
                                    Logout
                                </button>
                            }
                        </li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Servizi", "AllServices", "Services", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Prenota", "Index", "Reservations", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Contatti", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Login", "Login", "Auth", new { area = "" }, new { @class = "nav-link ml-auto" })</li>
                    }
                </ul>
            </div>
        </div>
    </nav>
    <div @*class="body-content"*@>
        @RenderBody()
        <hr />
        <footer class="text-center">
            <p>&copy; @DateTime.Now.Year - LeBarbier</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>